import { StyleSheet } from "react-native";

import { theme } from "./theme";

export const styles = StyleSheet.create({
  containerShadow: {
    position: "absolute",
    zIndex: theme.zindex.back,
    top: 6,
    left: 6,
    width: "100%",
    height: "100%",
    backgroundColor: theme.colors.shadow,
  },
  buttonShadow: {
    position: "absolute",
    zIndex: theme.zindex.back,
    top: 3,
    left: 3,
    width: 32,
    height: 32,
    width: "100%",
    height: "100%",
    backgroundColor: theme.colors.shadow,
  },
  container: {
    backgroundColor: theme.colors.card,
    borderWidth: 3,
    borderColor: theme.colors.border,
    zIndex: theme.zindex.front,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 24,
    backgroundColor: theme.colors.pink,
  },
  title: {
    fontSize: theme.font.size.l,
    fontFamily: theme.font.family.main,
    color: theme.colors.primary,
  },
  menu: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: -24,
    padding: 24,
    backgroundColor: theme.colors.pink,
  },
  navButton: {
    width: 32,
    height: 32,
    backgroundColor: theme.colors.lavender,
    borderWidth: 1,
    borderColor: theme.colors.border,
    justifyContent: "center",
    alignItems: "center",
    zIndex: theme.zindex.front,
  },

  navButtonText: {
    fontSize: theme.font.size.l,
    fontFamily: theme.font.family.main,
    color: theme.colors.primary,
  },
  monthLabel: {
    fontSize: theme.font.size.l,
    fontFamily: theme.font.family.main,
    zIndex: theme.zindex.front,
    backgroundColor: theme.colors.background,
    padding: 12,
    borderWidth: 2,
  },
  weekRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderColor: theme.colors.border,
    padding: 12,
  },
  weekDay: {
    width: "14.28%",
    textAlign: "center",
    fontSize: theme.font.size.s,
    fontFamily: theme.font.family.main,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 6,
  },
  day: {
    width: "14.28%",
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.card,
  },
  dayText: {
    fontSize: theme.font.size.s,
    fontFamily: theme.font.family.main,
  },
  legend: {
    backgroundColor: theme.colors.mint,
    borderTopColor: theme.colors.border,
    borderTopWidth: 3,
    padding: 12,
    gap: 3,
  },
  legendRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  legendText: {
    fontFamily: theme.font.family.main,
    fontSize: theme.font.size.s,
  },
  legendIcon: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginRight: 6,
  },
  alertContainer: { marginTop: 12 },
  alert: {
    borderWidth: 3,
    borderColor: theme.colors.border,
    padding: 10,
    backgroundColor: "#ffdddd",
    zIndex: theme.zindex.front,
  },
  alertText: {
    fontSize: theme.font.size.s,
    fontFamily: theme.font.family.main,
  },
  modal: {
    justifyContent: "center",
    padding: 56,
    backgroundColor: theme.colors.background,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 8,
    marginVertical: 10,
    fontSize: theme.font.size.s,
    fontFamily: theme.font.family.main,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 6,
  },
});
